"""reliability: audit chain and persisted traces

Revision ID: 67837e0c5670
Revises: 581448aea3b8
Create Date: 2026-08-06 13:59:09.875182

"""
from typing import Sequence, Union

import hashlib

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67837e0c5670'
down_revision: Union[str, None] = '581448aea3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _canonical_ts(ts) -> str:
    """Must mirror app.repositories.audit_repository._canonical_ts exactly,
    otherwise chained hashes produced here can never verify at runtime."""
    if getattr(ts, "tzinfo", None) is not None:
        ts = ts.astimezone(__import__("datetime").timezone.utc).replace(tzinfo=None)
    return ts.strftime("%Y-%m-%dT%H:%M:%S.%f")


def _chain_hash(prev_hash: str, entry_id: str, user_id: str, action: str,
                status: str, timestamp: str, details: str) -> str:
    raw = f"{prev_hash}|{entry_id}|{user_id}|{action}|{status}|{timestamp}|{details}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('traces',
    sa.Column('trace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('org', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('input_preview', sa.Text(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('spans_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('trace_id')
    )
    op.create_index(op.f('ix_traces_org'), 'traces', ['org'], unique=False)
    op.create_index(op.f('ix_traces_status'), 'traces', ['status'], unique=False)
    op.create_index(op.f('ix_traces_user_id'), 'traces', ['user_id'], unique=False)
    op.add_column('audit_log', sa.Column('prev_hash', sa.String(length=64), nullable=False, server_default=''))
    # ### end Alembic commands ###

    # Backfill the tamper-evident chain for pre-existing audit rows (old
    # standalone entry_hash values are replaced by chained hashes).
    conn = op.get_bind()
    rows = conn.execute(sa.text(
        "SELECT entry_id, timestamp, user_id, action, status, details "
        "FROM audit_log ORDER BY timestamp, entry_id"
    )).mappings().all()
    prev_hash = ""
    for row in rows:
        entry_hash = _chain_hash(
            prev_hash,
            row["entry_id"],
            row["user_id"],
            row["action"],
            row["status"],
            _canonical_ts(row["timestamp"]),
            row["details"] or "",
        )
        conn.execute(
            sa.text("UPDATE audit_log SET entry_hash = :h, prev_hash = :p WHERE entry_id = :id"),
            {"h": entry_hash, "p": prev_hash, "id": row["entry_id"]},
        )
        prev_hash = entry_hash


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit_log', 'prev_hash')
    op.drop_index(op.f('ix_traces_user_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_status'), table_name='traces')
    op.drop_index(op.f('ix_traces_org'), table_name='traces')
    op.drop_table('traces')
    # ### end Alembic commands ###
